"""Enforce CLAUDE.md rule 1: hidden truth is never readable by workflows.

Ground truth is written only to ``truth_store/<id>/`` — a separate top-level tree, not a
subdirectory of the run (the lead's ruling of 2026-09-04). The rule is enforced three times
over, because each layer alone is weak in a way the next one covers:

**Structurally.** ``runs/<id>/`` holds the observations, the redacted manifest and the call
log, and nothing else. A workflow rooted there has nothing to escape *to*. This is the
layer the review's two bypasses would have hit: it does not depend on the loader being
right, which is exactly why it is first.

**Statically.** Nothing under ``workflows/`` may import a ``truth``/``truth_store`` module
or reference a path with either as a segment — nor, since the lead's ruling B5 of
2026-09-10, the ``scenarios`` package or a path with ``scenarios`` as a segment: the
committed scenario files publish the answer key (baseline → ``correct_conclusion``) as
plainly as the truth store does. The check is AST-based, so it covers code that is never
executed in tests. Its blind spot is a path assembled at run time — and, as the review
showed, an attribute handed out by an API, which spells nothing at all.

**On the real API.** The last part of this file drives :func:`state.run_view.open_run` —
the loader a workflow actually uses — against a run generated by the harness, and asks it
for hidden truth in every way a caller could: by relative path, by traversal, by ``"."``
and ``""``, by absolute path, by symlink, by listing, by every public attribute and method
the object exposes, by looking for the run root anywhere on the object at all (it is in a
closure, not an attribute), and by reading the manifest fields that would give the answer
away.
All of it fails; the same run's truth is shown to be on disk and readable by anything that
is not the loader; and a **negative control** asserts that a legitimate read still
succeeds, so the test cannot pass by refusing everything.

The checker is exercised against synthetic violating and clean files first, so the static
half cannot pass simply because ``workflows/`` is still mostly empty.
"""

from __future__ import annotations

import ast
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
WORKFLOWS_DIR = REPO_ROOT / "workflows"

# A path-like string literal with "truth", "truth_store" or "scenarios" as a segment:
# "runs/x/truth/", "/truth", "truth_store/params.json", "scenarios/S6-01.yaml", or the bare
# segment (as in Path(run) / "truth"). ``scenarios`` joined the list on the lead's ruling B5
# (2026-09-10): the scenario files name the baseline and the answer key of every row.
_TRUTH_PATH = re.compile(r"(?i)(^|[/\\])(truth(_store)?|scenarios|eval|eval\.yaml)([/\\]|$)")

# ``eval`` joined both sets with the evaluation suite (milestone 6, 2026-09-22): the scorer
# is the code no workflow may access (§6.7), so a workflow importing or reading ``eval/``
# is a finding by path as well as by import (the allow-list below already bars the import;
# the path rule closes ``open("eval/...")``, the bare segment and ``configs/eval.yaml``, the
# scorer's own thresholds -- named here so it is caught by the path rule and not, as it
# happened to be, by the dotted-module regex matching ``eval.yaml``).
# ``distinguish`` joined them with the distinguishability analysis (2026-09-24): it reads
# answer keys and writes ``admissible.json`` beside them, so it is the scorer's side too.
_TRUTH_MODULES = frozenset({"truth", "truth_store", "scenarios", "eval", "distinguish"})

# The layout API hands out the truth tree without spelling "truth" in any path literal:
# ``RunPaths.for_run(id).truth``, ``truth_store_for(runs_root)`` and ``TRUTH_STORE_DIR`` are
# names, not strings, so the path regex never saw them and the review's 3-line workflow
# read ``faults.json`` with zero violations (finding B4, 2026-09-10). A workflow has no
# business in :mod:`sim.run.layout` at all -- its loader is :func:`state.run_view.open_run`
# -- so any import from that module is flagged, as is any of these names however reached,
# and any attribute access spelled ``truth...`` on any object.
_LAYOUT_MODULE = "sim.run.layout"
_TRUTH_NAMES = frozenset({"truth_store_for", "TRUTH_STORE_DIR", "TRUTH_STORE", "RunPaths"})
_TRUTH_ATTR = re.compile(r"(?i)^truth")

# The whole-branch review of 2026-09-12 (blocker 1) showed that a deny-list of tokens is
# the wrong shape: a module importing only ``sim.run.matrix.load_library``,
# ``sim.run.harness.generate_run``, ``sim.plants.load_plant_config`` and
# ``state.run_view.open_run`` spelled none of the denied tokens, passed this checker with
# [], and -- given only ``runs/<id>/`` -- read every scenario's answer key and seed through
# ``load_library`` and, by regenerating candidate cells with ``write=False`` and matching
# ``sensors.json`` bit for bit, recovered the run's scenario id, level and all five derived
# seeds (``_SNEAKY_SOURCE`` below is that module). So the checker is now an ALLOW-LIST: a
# module under ``workflows/`` may import the standard library, numpy, scipy, pydantic, the
# tool registry (``tools``), its own package (``workflows``, relative imports included) and
# the workflow-facing run view (``state.run_view``; from ``state`` itself only the names the
# package exports for workflows). Every other import -- all of ``sim``, ``scenarios``,
# ``anchor``, ``eval``, ``state.provenance``, whatever is added later -- is a finding
# without anyone having to foresee it. The deny rules above stay as a second layer.
_STDLIB_MODULES = frozenset(sys.stdlib_module_names)
_ALLOWED_TOP_LEVEL = frozenset({"tools", "workflows", "numpy", "scipy", "pydantic"})
_RUN_VIEW_MODULE = "state.run_view"
_WORKFLOW_FACING_STATE_NAMES = frozenset({"RunView", "TruthAccessError", "open_run"})

# Names of the generation machinery and of the two manifest fields a workflow must never
# hold (the redacted manifest has neither): a finding as a bare name or as an attribute.
_DENIED_TOKENS = frozenset(
    {"scenario_id", "seeds", "load_library", "generate_run", "generate_cells", "RunManifest"}
)

# Round two of blocker 1 (the coordinator, 2026-09-12 15:30): the allow-list covers import
# STATEMENTS only. ``importlib.import_module("sim.run." + "matrix")``, ``__import__``,
# ``sys.modules``, ``exec(compile(src, ...))`` and a second interpreter through
# ``subprocess`` all reached the generator with the allow-list returning []. A workflow
# module has no legitimate use for dynamic import or code execution, so these are denied by
# NAME and ATTRIBUTE wherever they appear, and a string literal -- or a concatenation of
# literals -- that spells a forbidden module path is a finding too. Recorded with its limit
# in the decisions log: a static checker cannot prove the absence of every dynamic route; the
# structural defence is a workflow process in which ``sim``, ``scenarios/`` and
# ``truth_store/`` are not importable or readable at all (deferred to the tool-registry and
# workflow-harness components).
_DENIED_MODULES = frozenset(
    {"importlib", "runpy", "subprocess", "ctypes", "pkgutil", "builtins"}
    | {"codecs", "base64", "binascii", "zlib", "marshal", "pickle"}
)
_DENIED_CALLABLES = frozenset({"__import__", "exec", "eval", "compile"})
_DENIED_OS_ATTRS = re.compile(r"^(system|popen|exec\w*|spawn\w*)$")
_DYNAMIC_ATTR_CALLS = frozenset({"getattr", "setattr", "delattr"})
# a module path a workflow must not spell: the exact name, or a dotted path under it, or an
# import statement of it inside a string (code handed to exec or a second interpreter)
_FORBIDDEN_MODULE_ROOTS = (
    "sim",
    "scenarios",
    "anchor",
    "eval",
    "distinguish",
    "state.provenance",
    "state",
)
_MODULE_LITERAL = re.compile(
    r"(?<![\w.])(?:sim|scenarios|anchor|eval|state\.provenance)\.[A-Za-z_][\w.]*"
    r"|\b(?:import|from)\s+(?:sim|scenarios|anchor|eval|state\.provenance|state)\b"
)


# Round three, the LAST hardening round (the coordinator, 2026-09-12 18:10): a module name
# assembled from ``chr`` codes and handed to ``__builtins__["__import__"]``, the builtins
# reached through ``open_run.__globals__``, and ``open_run.__globals__`` itself all passed
# the round-two checker (the second only as a module literal). Dunder access and obfuscated
# literals have no use in a workflow, so: every ``__x__`` as a name, an attribute or a string
# literal is a finding except ``__name__``, ``__doc__``, ``__file__``, ``__version__``,
# ``__main__`` (the idiom), ``__all__`` (an export list) and ``__init__`` as an attribute
# (``super().__init__()``); ``vars``, ``globals``, ``locals``, ``dir`` and ``chr`` are
# findings as calls; ``.decode`` and ``.fromhex`` as attributes; ``codecs``, ``base64``,
# ``binascii``, ``zlib``, ``marshal``, ``pickle`` by any import spelling or as names. Hardening
# stops here by the coordinator's instruction: the record (decisions, card §4.1) says a
# static checker cannot close every route and names the structural defence.
_DUNDER = re.compile(r"^__\w+__$")
_ALLOWED_DUNDER_NAMES = frozenset({"__name__", "__doc__", "__file__", "__version__", "__all__"})
_ALLOWED_DUNDER_ATTRS = frozenset({"__name__", "__doc__", "__file__", "__version__", "__init__"})
_ALLOWED_DUNDER_LITERALS = frozenset({"__name__", "__doc__", "__file__", "__version__", "__main__"})
_DENIED_INTROSPECTION = frozenset({"vars", "globals", "locals", "dir", "chr"})
_DENIED_DECODE_ATTRS = frozenset({"decode", "fromhex"})
_DENIED_ENCODING_MODULES = frozenset({"codecs", "base64", "binascii", "zlib", "marshal", "pickle"})


def _denied_dunder(text: str, allowed: frozenset[str]) -> bool:
    return bool(_DUNDER.match(text)) and text not in allowed


def _folded_string(node: ast.AST) -> str | None:
    """A string constant, or a ``+`` chain of string constants folded, else None."""
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    if isinstance(node, ast.BinOp) and isinstance(node.op, ast.Add):
        left, right = _folded_string(node.left), _folded_string(node.right)
        if left is not None and right is not None:
            return left + right
    return None


def _spells_forbidden_module(text: str) -> bool:
    stripped = text.strip()
    return stripped in _FORBIDDEN_MODULE_ROOTS or bool(_MODULE_LITERAL.search(text))


def _module_denied(module: str) -> bool:
    """``importlib``, ``importlib.util``, ``subprocess``, ... by any import spelling."""
    return module.split(".", 1)[0] in _DENIED_MODULES


def _import_allowed(module: str, names: frozenset[str], level: int) -> bool:
    """Whether one import statement is on the allow-list."""
    if level > 0:  # relative: stays inside workflows/, every module of which is checked
        return True
    top = module.split(".", 1)[0]
    if top in _STDLIB_MODULES or top in _ALLOWED_TOP_LEVEL:
        return True
    if module == _RUN_VIEW_MODULE:
        return True
    if module == "state":
        # ``from state import open_run`` is fine; ``from state import run_view`` too;
        # ``from state import CallLog`` (the provenance log) or ``import state`` is not
        return bool(names) and names <= (_WORKFLOW_FACING_STATE_NAMES | {"run_view"})
    return False


@dataclass(frozen=True)
class Violation:
    """One forbidden reference to hidden truth."""

    path: Path
    line: int
    kind: str
    detail: str

    def __str__(self) -> str:
        """Format as file:line: kind: detail."""
        return f"{self.path}:{self.line}: {self.kind}: {self.detail}"


def _docstring_nodes(tree: ast.AST) -> set[int]:
    """Return ids of string constants that are docstrings, which are exempt."""
    exempt: set[int] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Module | ast.ClassDef | ast.FunctionDef | ast.AsyncFunctionDef):
            body = node.body
            if (
                body
                and isinstance(body[0], ast.Expr)
                and isinstance(body[0].value, ast.Constant)
                and isinstance(body[0].value.value, str)
            ):
                exempt.add(id(body[0].value))
    return exempt


def find_truth_references(path: Path) -> list[Violation]:
    """Statically find imports of, or path references to, hidden truth in one module.

    Args:
        path: A Python source file.

    Returns:
        Every violation found, in source order.
    """
    source = path.read_text(encoding="utf-8")
    tree = ast.parse(source, filename=str(path))
    exempt = _docstring_nodes(tree)
    found: list[Violation] = []

    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            # ``import a.b, c`` is one statement; one finding if any alias is off the list
            bad = [
                alias.name
                for alias in node.names
                if not _import_allowed(alias.name, frozenset(), 0)
                or _module_denied(alias.name)
                or _TRUTH_MODULES & set(alias.name.lower().split("."))
                or alias.name.startswith(_LAYOUT_MODULE)
            ]
            if bad:
                found.append(Violation(path, node.lineno, "import", ", ".join(bad)))
        elif isinstance(node, ast.ImportFrom):
            module = node.module or ""
            segments = set(module.lower().split(".")) if module else set()
            names = {alias.name.lower() for alias in node.names}
            raw_names = frozenset(alias.name for alias in node.names)
            imports_layout = module.startswith(_LAYOUT_MODULE) or (
                module == _LAYOUT_MODULE.rsplit(".", 1)[0] and "layout" in names
            )
            if (
                not _import_allowed(module, raw_names, node.level)
                or _module_denied(module)
                or _TRUTH_MODULES & (segments | names)
                or imports_layout
                or _TRUTH_NAMES & raw_names
                or _DENIED_TOKENS & raw_names
                or _DENIED_CALLABLES & raw_names
            ):
                names_str = ", ".join(alias.name for alias in node.names)
                found.append(
                    Violation(path, node.lineno, "import", f"from {node.module} import {names_str}")
                )
        elif isinstance(node, ast.Name) and (
            node.id in _TRUTH_NAMES
            or node.id in _DENIED_TOKENS
            or node.id in _DENIED_CALLABLES
            or node.id in _DENIED_MODULES
        ):
            found.append(Violation(path, node.lineno, "name", node.id))
        elif isinstance(node, ast.Attribute) and (
            _TRUTH_ATTR.search(node.attr)
            or node.attr in _TRUTH_NAMES
            or node.attr in _DENIED_TOKENS
            or (
                isinstance(node.value, ast.Name)
                and node.value.id == "sys"
                and node.attr == "modules"
            )
            or (
                isinstance(node.value, ast.Name)
                and node.value.id == "os"
                and _DENIED_OS_ATTRS.match(node.attr)
            )
        ):
            found.append(Violation(path, node.lineno, "attribute", f".{node.attr}"))
        elif (
            isinstance(node, ast.Call)
            and isinstance(node.func, ast.Name)
            and node.func.id in _DYNAMIC_ATTR_CALLS
            and (
                len(node.args) < 2
                or not isinstance(node.args[0], ast.Name | ast.Attribute)
                or not (
                    isinstance(node.args[1], ast.Constant) and isinstance(node.args[1].value, str)
                )
            )
        ):
            found.append(Violation(path, node.lineno, "dynamic attribute", f"{node.func.id}(...)"))
        elif (
            isinstance(node, ast.BinOp)
            and (folded := _folded_string(node)) is not None
            and _spells_forbidden_module(folded)
        ):
            found.append(Violation(path, node.lineno, "module literal", repr(folded)))
        elif (
            isinstance(node, ast.Constant)
            and isinstance(node.value, str)
            and id(node) not in exempt
            and _TRUTH_PATH.search(node.value)
        ):
            found.append(Violation(path, node.lineno, "path literal", repr(node.value)))
        if (
            isinstance(node, ast.Constant)
            and isinstance(node.value, str)
            and id(node) not in exempt
            and _spells_forbidden_module(node.value)
        ):
            found.append(Violation(path, node.lineno, "module literal", repr(node.value)))

        # round three: dunder access, introspection and obfuscated literals, as a separate
        # chain so that a node already reported above can be reported for this as well
        if isinstance(node, ast.Name) and (
            _denied_dunder(node.id, _ALLOWED_DUNDER_NAMES) or node.id in _DENIED_ENCODING_MODULES
        ):
            found.append(Violation(path, node.lineno, "dunder name", node.id))
        elif isinstance(node, ast.Attribute) and (
            _denied_dunder(node.attr, _ALLOWED_DUNDER_ATTRS) or node.attr in _DENIED_DECODE_ATTRS
        ):
            found.append(Violation(path, node.lineno, "dunder attribute", f".{node.attr}"))
        elif (
            isinstance(node, ast.Constant)
            and isinstance(node.value, str)
            and id(node) not in exempt
            and _denied_dunder(node.value.strip(), _ALLOWED_DUNDER_LITERALS)
        ):
            found.append(Violation(path, node.lineno, "dunder literal", repr(node.value)))
        elif (
            isinstance(node, ast.Call)
            and isinstance(node.func, ast.Name)
            and node.func.id in _DENIED_INTROSPECTION
        ):
            found.append(Violation(path, node.lineno, "introspection", f"{node.func.id}(...)"))

    return found


def workflow_modules() -> list[Path]:
    """Every Python module under workflows/, recursively."""
    return sorted(WORKFLOWS_DIR.rglob("*.py"))


# --- self-check: the checker must catch each forbidden pattern -----------------------

_VIOLATING_SOURCE = '''
"""Docstring mentioning runs/<id>/truth/ is allowed."""
import sim.truth
from sim import truth
from sim.truth.model import TruthModel
from sim.truth_store import load_truth
from pathlib import Path

def load(run: Path):
    a = open(run / "truth" / "params.json")
    b = open(f"{run}/truth/labels.json")
    c = open("/data/runs/abc/TRUTH/x.yaml")
    d = run.joinpath("truth")
    e = open("truth_store/run_abc/parameters.json")
    return a, b, c, d, e
'''

_CLEAN_SOURCE = '''
"""Ground truth is discussed here in a docstring only; that is fine."""
from pathlib import Path

from tools import registry

def load(run: Path):
    # "truthful" and "untruth" are not path segments and must not be flagged.
    label = "truthful"
    obs = open(run / "observations.csv")
    return registry, label, obs, "untruth"
'''


def test_checker_catches_every_forbidden_pattern(tmp_path: Path):
    bad = tmp_path / "bad_workflow.py"
    bad.write_text(_VIOLATING_SOURCE, encoding="utf-8")
    kinds = [v.kind for v in find_truth_references(bad)]
    assert kinds.count("import") == 4, kinds
    # "truth" (joined), "/truth/" (f-string part), "/TRUTH/", "truth" (joinpath),
    # "truth_store/..." (the tree hidden truth actually lives in)
    assert kinds.count("path literal") == 5, kinds


def test_checker_ignores_docstrings_and_near_misses(tmp_path: Path):
    good = tmp_path / "good_workflow.py"
    good.write_text(_CLEAN_SOURCE, encoding="utf-8")
    assert find_truth_references(good) == []


# The review's own bypass, verbatim in shape (finding B4): three lines, no string with
# "truth" in it, and before 2026-09-10 find_truth_references returned [] on it while the
# module then read S6-01's answer key.
_LAYOUT_BYPASS_SOURCE = """
from sim.run.layout import RunPaths
paths = RunPaths.for_run("run_6ebcad561b75")
labels = open(paths.truth / "faults.json").read()
"""

# Each remaining way of reaching the truth tree through the layout API, one per line, so
# a checker that catches the import alone cannot pass this.
_LAYOUT_VARIANTS_SOURCE = """
import sim.run.layout as layout
from sim.run import layout as lay2
from sim.run.layout import truth_store_for, TRUTH_STORE_DIR
a = layout.truth_store_for("runs")
b = lay2.TRUTH_STORE
c = something().truth_manifest
d = other.truth
"""

# What a workflow is actually given, and it must stay clean: the loader, and a read of the
# visible record through it. "truthful" is not an attribute spelled truth-anything.
_LOADER_ONLY_SOURCE = """
from state.run_view import open_run

def load(run_dir):
    view = open_run(run_dir)
    sensors = view.sensors()
    log = view.read_text("../calls.jsonl") if False else None
    label = view.manifest.plant
    return sensors, log, label
"""


def test_checker_catches_the_layout_api_bypass(tmp_path: Path):
    """Finding B4: the truth tree reached by name, with no truth-spelling string anywhere."""
    bad = tmp_path / "layout_bypass.py"
    bad.write_text(_LAYOUT_BYPASS_SOURCE, encoding="utf-8")
    found = find_truth_references(bad)
    kinds = sorted(v.kind for v in found)
    assert "import" in kinds, found  # from sim.run.layout import RunPaths
    assert "attribute" in kinds, found  # paths.truth
    assert kinds.count("name") >= 1, found  # RunPaths used
    # every violation is on a line that spells no "truth" path literal -- the point
    assert not any(v.kind == "path literal" for v in found), found


def test_checker_catches_every_layout_route(tmp_path: Path):
    bad = tmp_path / "layout_variants.py"
    bad.write_text(_LAYOUT_VARIANTS_SOURCE, encoding="utf-8")
    found = find_truth_references(bad)
    lines = {v.line for v in found}
    # the two module imports, the from-import, and each of the four uses: seven lines
    assert lines == {2, 3, 4, 5, 6, 7, 8}, sorted(str(v) for v in found)


def test_checker_leaves_the_loader_alone(tmp_path: Path):
    """The negative control: what a workflow is given must not be flagged."""
    good = tmp_path / "loader_only.py"
    good.write_text(_LOADER_ONLY_SOURCE, encoding="utf-8")
    assert find_truth_references(good) == []


# Ruling B5 (iii): the scenario files are the answer key, so every route to them is a
# violation -- the package by either import form, its schema module, a path literal in
# every spelling, and the truth-side plant record (which spells ``truth`` and is caught by
# the rule that already existed). One route per line.
_SCENARIOS_SOURCE = """
import scenarios
from scenarios.schema import load_scenario
from scenarios import schema
import scenarios.schema as sc
a = open("scenarios/S6-01.yaml")
b = open("../scenarios/S6-01.yaml")
c = Path(root) / "scenarios"
d = open("/repo/SCENARIOS/S6-04.yaml")
e = open("sim/plants/truth/plant_A.yaml")
f = sim.plants.truth.load_plant_truth(plant)
"""

# Words that merely contain "scenario" are not routes to the files and must stay clean.
_SCENARIO_WORDS_SOURCE = """
from state.run_view import open_run

def diagnose(run_dir):
    view = open_run(run_dir)
    scenario_guess = "the scenario is probably a sensor drift"
    label = "scenarios are not readable; only the record is"
    return view.sensors(), scenario_guess, label, "my_scenarios.txt"
"""


def test_checker_bars_every_route_to_the_scenario_files(tmp_path: Path):
    """Ruling B5 (iii): the scenario package and directory are as forbidden as the truth store."""
    bad = tmp_path / "scenario_reader.py"
    bad.write_text(_SCENARIOS_SOURCE, encoding="utf-8")
    found = find_truth_references(bad)
    lines = {v.line for v in found}
    assert lines == {2, 3, 4, 5, 6, 7, 8, 9, 10, 11}, sorted(str(v) for v in found)
    kinds = [v.kind for v in found]
    assert kinds.count("import") == 4, kinds
    assert kinds.count("path literal") >= 5, kinds


def test_checker_leaves_the_word_scenario_alone(tmp_path: Path):
    """The negative control for B5 (iii): prose and file names are not the package."""
    good = tmp_path / "scenario_words.py"
    good.write_text(_SCENARIO_WORDS_SOURCE, encoding="utf-8")
    assert find_truth_references(good) == []


# The reviewer's module of the whole-branch review of 2026-09-12 (blocker 1), reconstructed
# from its description: no ``truth``, no ``scenarios``, no ``layout``, no denied name of the
# 2026-09-10 checker anywhere in it, so that checker returned []. Given only the visible
# ``runs/<id>/`` it reads every scenario's answer key and seed through ``load_library`` and,
# by regenerating candidate cells with ``write=False`` and matching ``sensors.json`` bit for
# bit, recovers the run's scenario id, level and all five derived seeds. It must fail.
_SNEAKY_SOURCE = '''
"""Only public loaders; none of the old tokens. Recovers the answer key of a run."""
from pathlib import Path

import numpy as np

from sim.plants import load_plant_config
from sim.run.harness import generate_run
from sim.run.matrix import load_library
from state.run_view import open_run


def identify(run_dir):
    view = open_run(run_dir)
    seen = view.sensors()
    plant = load_plant_config(view.manifest.plant)
    tier = view.manifest.tier
    for sid, row in load_library().items():
        cell = generate_run(row, tier, plant=plant, write=False)
        same = all(
            np.array_equal(cell.record[name].value, np.asarray(series["value"]))
            for name, series in seen.items()
        )
        if same:
            return sid, row.level, row.correct_conclusion, cell.manifest.seeds
    return None
'''

# The old checker's tokens, spelled out so the fixture provably contains none of them: this
# is what made the module invisible to a deny-list.
_OLD_CHECKER_TOKENS = ("truth", "scenarios", "layout", "RunPaths", "TRUTH_STORE")


def test_the_reviewers_regeneration_oracle_is_a_finding(tmp_path: Path):
    """Blocker 1 of the 2026-09-12 review: the allow-list catches what the deny-list missed."""
    lowered = _SNEAKY_SOURCE.lower()
    assert not any(tok.lower() in lowered for tok in _OLD_CHECKER_TOKENS), (
        "the fixture must spell none of the old tokens, or it does not reproduce the bypass"
    )
    bad = tmp_path / "sneaky_workflow.py"
    bad.write_text(_SNEAKY_SOURCE, encoding="utf-8")
    found = find_truth_references(bad)
    details = " ".join(str(v) for v in found)
    # the three imports off the allow-list, each its own finding; the run view is allowed
    imports = [v for v in found if v.kind == "import"]
    assert len(imports) == 3, imports
    assert "state.run_view" not in " ".join(v.detail for v in imports)
    assert all(v.detail.startswith("from sim.") for v in imports), imports
    # and the generation machinery by name, however it was imported
    for token in ("load_library", "generate_run", ".seeds"):
        assert token in details, (token, details)
    assert not any(v.kind == "path literal" for v in found), found


# Everything the allow-list admits, in one module, must stay clean: the standard library,
# numpy/scipy/pydantic, the tool registry, the workflow package itself (absolute and
# relative) and the run view by either spelling.
_ALLOWED_IMPORTS_SOURCE = """
import json
import os.path
from collections import Counter
from dataclasses import dataclass

import numpy as np
import scipy.optimize
from pydantic import BaseModel

import tools
from tools import registry
from tools.registry import call
import workflows.p0_scripted
from . import helpers
from .helpers import step
from state.run_view import open_run, RunView
from state import open_run as open_run_again
import state.run_view
"""

# ... and everything just outside it is a finding: the simulator by any route, the
# scenario package, the anchor and evaluation internals, the provenance log, the whole
# state package by bare import, and the denied names as bare names or attributes.
_DISALLOWED_IMPORTS_SOURCE = """
import sim
import sim.run.harness
from sim.run.matrix import load_library
from sim.plants import load_plant_config
from sim.observation import observe
import anchor.compare_generated
from eval import metrics
from state.provenance import CallLog
from state import CallLog
import state
x = manifest.scenario_id
y = something.seeds
z = generate_cells(a, b, c)
w = RunManifest
"""


def test_checker_admits_exactly_the_workflow_facing_surface(tmp_path: Path):
    good = tmp_path / "allowed_imports.py"
    good.write_text(_ALLOWED_IMPORTS_SOURCE, encoding="utf-8")
    assert find_truth_references(good) == []


def test_checker_flags_every_import_outside_the_allow_list(tmp_path: Path):
    bad = tmp_path / "disallowed_imports.py"
    bad.write_text(_DISALLOWED_IMPORTS_SOURCE, encoding="utf-8")
    found = find_truth_references(bad)
    lines = {v.line for v in found}
    assert lines == set(range(2, 16)), sorted(str(v) for v in found)
    kinds = [v.kind for v in found]
    assert kinds.count("import") == 10, kinds
    assert kinds.count("attribute") == 2 and kinds.count("name") == 2, kinds


# Round two (the coordinator, 2026-09-12 15:30 UTC): six modules tried against the
# allow-list of the first round, four of which it passed. Their exact sources. Every one of
# (1)-(4) and (6) must be a finding naming its route; (5) was already reported and stays as
# the positive control.
_DYNAMIC_ROUTES: dict[str, tuple[str, tuple[str, ...]]] = {
    "b1_importlib.py": (
        """
import importlib
m = importlib.import_module("sim.run." + "matrix")
lib = getattr(m, "load_" + "library")()
""",
        ("importlib", "'sim.run.matrix'", "getattr(...)"),
    ),
    "b2_dunder.py": (
        """
h = __import__("sim.run.harness", fromlist=["x"])
gen = getattr(h, "generate" + "_run")
""",
        ("__import__", "'sim.run.harness'", "getattr(...)"),
    ),
    "b3_sysmodules.py": (
        """
import sys, numpy as np
from state.run_view import open_run
mod = sys.modules.get("sim.run.matrix") or __import__("sim.run.matrix", fromlist=["x"])
""",
        (".modules", "__import__", "'sim.run.matrix'"),
    ),
    "b4_exec.py": (
        """
from state.run_view import open_run
src = "from sim.run.matrix import load_library\\nlib = load_library()"
exec(compile(src, "<x>", "exec"))
""",
        ("exec", "compile", "from sim.run.matrix import"),
    ),
    "b5_pathlib.py": (
        """
import pathlib, yaml
from state.run_view import open_run
root = pathlib.Path(__file__).resolve().parents[1]
files = sorted((root / "scen" "arios").glob("*.yaml"))
""",
        ("yaml", "'scenarios'"),
    ),
    "b6_subprocess.py": (
        "\nimport subprocess, sys\nfrom state.run_view import open_run\n"
        'out = subprocess.run([sys.executable, "-c", '
        '"from sim.run.matrix import load_library; print(load_library())"], '
        "capture_output=True, text=True).stdout\n",
        ("subprocess", "from sim.run.matrix import"),
    ),
}


@pytest.mark.parametrize("filename", sorted(_DYNAMIC_ROUTES))
def test_every_dynamic_route_of_the_second_round_is_a_finding(tmp_path: Path, filename: str):
    source, expected = _DYNAMIC_ROUTES[filename]
    bad = tmp_path / filename
    bad.write_text(source, encoding="utf-8")
    found = find_truth_references(bad)
    assert found, filename
    details = "\n".join(str(v) for v in found)
    for token in expected:
        assert token in details, (filename, token, details)
    # the run view is never what is reported
    assert "state.run_view" not in " ".join(v.detail for v in found if v.kind == "import")


# What the dynamic rules must NOT flag: a workflow reading its own attributes by a literal
# name, using ``os.path`` and ``sys.argv``, and strings that merely contain the words.
_DYNAMIC_CLEAN_SOURCE = """
import os.path
import sys
from state.run_view import open_run

def run(run_dir):
    view = open_run(run_dir)
    plant = getattr(view.manifest, "plant")
    args = sys.argv[1:]
    here = os.path.dirname(run_dir)
    note = "a simulation of the evaluation, anchored in state" + " of the art"
    return view, plant, args, here, note
"""


def test_the_dynamic_rules_leave_ordinary_code_alone(tmp_path: Path):
    good = tmp_path / "dynamic_clean.py"
    good.write_text(_DYNAMIC_CLEAN_SOURCE, encoding="utf-8")
    assert find_truth_references(good) == []


# Round three, the last (the coordinator, 2026-09-12 18:10 UTC): three more routes, exact
# sources. (7) and (9) passed the round-two checker; (8) was reported only as a module
# literal and must now be reported on its dunder route.
_LAST_ROUND_ROUTES: dict[str, tuple[str, tuple[str, ...]]] = {
    "b7_chr.py": (
        """
from state.run_view import open_run
name = "".join(chr(c) for c in (115, 105, 109, 46, 114, 117, 110, 46, 109, 97, 116, 114, 105, 120))
mod = __builtins__["__import__"](name) if isinstance(__builtins__, dict) else None
""",
        ("chr(...)", "__builtins__", "'__import__'"),
    ),
    "b8_lambda_builtins.py": (
        """
from state.run_view import open_run
imp = (lambda: getattr(open_run, "__globals__")["__builtins__"])()
load = imp["__import__"] if isinstance(imp, dict) else vars(imp)["__import__"]
m = load("sim.run.harness")
""",
        ("'__globals__'", "'__builtins__'", "vars(...)", "'__import__'", "'sim.run.harness'"),
    ),
    "b9_open_run_globals.py": (
        """
from state.run_view import open_run
g = open_run.__globals__
""",
        (".__globals__",),
    ),
}


@pytest.mark.parametrize("filename", sorted(_LAST_ROUND_ROUTES))
def test_every_route_of_the_last_round_is_a_finding(tmp_path: Path, filename: str):
    source, expected = _LAST_ROUND_ROUTES[filename]
    bad = tmp_path / filename
    bad.write_text(source, encoding="utf-8")
    found = find_truth_references(bad)
    assert found, filename
    details = "\n".join(str(v) for v in found)
    for token in expected:
        assert token in details, (filename, token, details)
    if filename == "b8_lambda_builtins.py":
        # the dunder route itself, not only the module literal at the end
        assert any(v.kind.startswith("dunder") for v in found), details


# Ordinary Python a workflow may well contain, which the dunder rules must leave alone: the
# main idiom, a module docstring and export list, a class with ``super().__init__()``,
# ``__version__`` and ``__file__``.
_DUNDER_CLEAN_SOURCE = '''
"""A workflow module with the usual dunders."""
from pathlib import Path

from state.run_view import open_run

__all__ = ["Step"]
__version__ = "0.1"
HERE = Path(__file__).parent


class Step(dict):
    def __init__(self, run_dir):
        super().__init__()
        self["view"] = open_run(run_dir)
        self["doc"] = __doc__


if __name__ == "__main__":
    Step(".")
'''


def test_the_dunder_rules_leave_ordinary_dunders_alone(tmp_path: Path):
    good = tmp_path / "dunder_clean.py"
    good.write_text(_DUNDER_CLEAN_SOURCE, encoding="utf-8")
    assert find_truth_references(good) == []


# --- the rule itself -------------------------------------------------------------


def test_workflows_layout_exists():
    assert WORKFLOWS_DIR.is_dir()
    for sub in ("p0_scripted", "p1_single_agent", "p2_multi_agent"):
        assert (WORKFLOWS_DIR / sub / "__init__.py").is_file(), sub


def test_no_workflow_module_references_hidden_truth():
    modules = workflow_modules()
    assert modules, "workflows/ contains no Python modules to check"
    violations = [v for path in modules for v in find_truth_references(path)]
    assert not violations, "workflows/ must not touch hidden truth:\n" + "\n".join(
        str(v) for v in violations
    )


# --- the rule on the real API ----------------------------------------------------
#
# Everything below drives the loader a workflow is actually given, on a run the harness
# actually generated. A static scan cannot show that this loader is unable to return
# truth; only asking it can.


@pytest.fixture(scope="module")
def generated_run(tmp_path_factory):
    """A real run on disk: truth written, observations written, manifest written."""
    from scenarios.schema import load_scenario
    from sim.plants import load_plant_config
    from sim.run.harness import generate_run

    scenario = load_scenario(REPO_ROOT / "scenarios" / "S2-03.yaml")
    scenario = scenario.model_copy(update={"duration_days": 40.0, "faults": ()})
    return generate_run(
        scenario,
        "B",
        plant=load_plant_config("C"),
        runs_root=tmp_path_factory.mktemp("store") / "runs",
    )


def test_the_truth_really_is_on_disk(generated_run):
    """The negative results below must not pass because there is nothing there."""
    truth = generated_run.paths.truth
    assert truth.is_dir()
    payload = json.loads(generated_run.paths.truth_faults.read_text(encoding="utf-8"))
    assert payload["scenario_id"] == "S2-03"
    assert payload["truth_label"] == ["sensor"]
    geometry = json.loads(generated_run.paths.truth_geometry.read_text(encoding="utf-8"))
    assert geometry["V_liq_true_m3"] > 0.0  # the hidden active volume, plainly readable


def test_the_truth_is_not_inside_the_run_directory(generated_run):
    """The structural half of the ruling: there is nothing above the observations to reach.

    The two bypasses the review demonstrated both worked by walking *up* from the
    observations directory. This asserts the layout that makes that pointless: hidden truth
    is in its own top-level tree, and ``runs/<id>/`` contains only the observations, the
    redacted manifest and the call log.
    """
    root = generated_run.paths.root
    truth = generated_run.paths.truth
    assert root not in truth.parents and truth != root
    assert truth.parent.name == "truth_store"
    assert truth.parent.parent == root.parent.parent  # sibling trees, one level up
    assert truth.name == root.name == generated_run.run_id

    inside = {p.relative_to(root).parts[0] for p in root.rglob("*")}
    assert inside == {"observations", "manifest.json", "calls.jsonl"}, sorted(inside)
    # nothing anywhere under the run directory carries a truth quantity
    assert not [p for p in root.rglob("*") if "truth" in p.name.lower()]


def test_the_manifest_under_runs_is_written_redacted(generated_run):
    """Not "redacted on the way out": the file itself never had the answer in it."""
    from sim.run.manifest import REDACTED_FIELDS

    visible = json.loads(generated_run.paths.manifest.read_text(encoding="utf-8"))
    assert not REDACTED_FIELDS & set(visible), sorted(REDACTED_FIELDS & set(visible))
    complete = json.loads(generated_run.paths.truth_manifest.read_text(encoding="utf-8"))
    assert set(complete) >= REDACTED_FIELDS, "the complete manifest belongs in the truth store"
    assert complete["scenario_id"] == "S2-03"
    # and no seed value has leaked into the visible file under another name
    from sim.run.seeds import STREAM_ORDER

    secret = {str(complete["seeds"][name]) for name in (*STREAM_ORDER, "base")}
    assert not secret & {str(v) for v in visible.values()}


# --- the adversarial bypass suite -------------------------------------------------
#
# Every route the review found, plus the ones it did not, plus a NEGATIVE CONTROL. A
# sandbox that refuses everything passes every refusal test ever written; the control is
# what makes the refusals mean something.


@pytest.mark.parametrize(
    "asked_for",
    [
        # traversal, in every spelling
        "../truth/faults.json",
        "../truth/parameters.json",
        "../../truth_store",
        "..",
        "../manifest.json",
        "./../truth/geometry.json",
        "../../etc/passwd",
        "subdir/../../manifest.json",
        # the scenario files and the truth-side plant record (ruling B5): outside the run
        # tree by construction, and refused by the same containment check
        "../../scenarios/S6-01.yaml",
        "../../../scenarios/S6-01.yaml",
        "../../../sim/plants/truth/plant_A.yaml",
        # the directory itself: `view.path(".")` was one of the two live bypasses, and it
        # returned a Path whose .parent was the run root
        ".",
        "./",
        "",
        "   ",
        # absolute
        "/etc/passwd",
        "/",
    ],
)
def test_the_workflow_loader_cannot_be_asked_for_truth(generated_run, asked_for):
    """Every spelling of "give me the truth" fails the same way."""
    from state.run_view import TruthAccessError, open_run

    view = open_run(generated_run.paths.root)
    with pytest.raises(TruthAccessError):
        view.read_text(asked_for)
    with pytest.raises(TruthAccessError):
        view.read_json(asked_for)


def test_the_loader_still_reads_what_it_is_for(generated_run):
    """NEGATIVE CONTROL. Without this the suite above passes by refusing everything."""
    from state.run_view import open_run

    view = open_run(generated_run.paths.root)
    record = view.read_json("sensors.json")
    assert record["sensors"], "the loader must still return the observations"
    assert view.read_text("feed_log.csv").startswith("day_d,")
    assert set(view.files) >= {"sensors.json", "feed_log.csv"}


def test_no_public_attribute_of_the_view_hands_over_a_path(generated_run):
    """The other live bypass: ``view.root / "truth" / "parameters.json"``.

    It wrote no forbidden string, so the static checker was blind to it. The rule that
    kills the whole class is that the view returns *contents*, never a path or a directory
    handle — so this walks every public attribute and no-argument method of the object and
    asserts none of them yields one.
    """
    from state.run_view import open_run

    view = open_run(generated_run.paths.root)
    public = [n for n in dir(view) if not n.startswith("_")]
    assert public, "the view exposes nothing at all, which would make this vacuous"

    checked = 0
    for name in public:
        value = getattr(view, name)
        if callable(value):
            try:
                value = value()
            except TypeError:  # takes arguments (e.g. read_text, sensor)
                continue
        checked += 1
        assert not isinstance(value, Path), f"view.{name} returns a Path"
        assert not any(isinstance(v, Path) for v in _leaves(value)), f"view.{name} yields a Path"
    assert checked >= 5, f"only {checked} accessors exercised"


def test_the_run_root_is_not_an_attribute_of_the_view(generated_run):
    """The lead's ruling E: the root is in a closure, not on the object.

    The review's live bypass was a *public* field. Making it private would have left the
    same object graph one underscore away, so there is no attribute at all — not `root`,
    not `_root`, and nothing whose value is the run directory or the observations
    directory.
    """
    from state.run_view import open_run

    view = open_run(generated_run.paths.root)
    for name in ("root", "_root", "_base", "path", "_resolve"):
        assert not hasattr(view, name), name

    # nothing stored on the object IS a path, under any name
    stored = {**getattr(view, "__dict__", {})}
    for field in getattr(view, "__dataclass_fields__", {}):
        stored[field] = getattr(view, field)
    for name, value in stored.items():
        assert not isinstance(value, Path | str), (name, value)

    # and the run directory does not appear as a value anywhere on it
    forbidden = {str(generated_run.paths.root), str(generated_run.paths.observations)}
    assert not forbidden & {str(v) for v in stored.values()}


def test_the_listing_and_the_resolver_agree(generated_run):
    """The lead's ruling E: `files` must not advertise what `read_text` will refuse.

    A planted symlink out of the tree used to be listed and then refused, so the view
    promised something it would not hand over.
    """
    from state.run_view import TruthAccessError, open_run

    link = generated_run.paths.observations / "planted.json"
    try:
        link.symlink_to(generated_run.paths.truth_faults)
    except (OSError, NotImplementedError):  # pragma: no cover - platform without symlinks
        pytest.skip("symlinks unavailable")
    try:
        view = open_run(generated_run.paths.root)
        assert "planted.json" not in view.files
        with pytest.raises(TruthAccessError):
            view.read_text("planted.json")
        # every listed file really is readable — the listing is not empty either
        assert view.files
        for name in view.files:
            assert view.read_text(name) is not None
    finally:
        link.unlink()


def _leaves(value: object, depth: int = 0) -> list[object]:
    """Every scalar reachable inside a returned container, to a bounded depth."""
    if depth > 3:
        return [value]
    if isinstance(value, dict):
        return [leaf for v in value.values() for leaf in _leaves(v, depth + 1)]
    if isinstance(value, list | tuple | set):
        return [leaf for v in value for leaf in _leaves(v, depth + 1)]
    return [value]


def test_a_symlink_out_of_the_observations_does_not_open_a_door(generated_run):
    """Resolution happens before the containment check, so a link is not an escape."""
    from state.run_view import TruthAccessError, open_run

    link = generated_run.paths.observations / "shortcut"
    try:
        link.symlink_to(generated_run.paths.truth, target_is_directory=True)
    except (OSError, NotImplementedError):  # pragma: no cover - platform without symlinks
        pytest.skip("symlinks unavailable")
    try:
        view = open_run(generated_run.paths.root)
        with pytest.raises(TruthAccessError):
            view.read_text("shortcut/faults.json")
        # and a link to a single file, which needs no directory traversal at all
        file_link = generated_run.paths.observations / "answers.json"
        file_link.symlink_to(generated_run.paths.truth_faults)
        try:
            with pytest.raises(TruthAccessError):
                view.read_text("answers.json")
        finally:
            file_link.unlink()
    finally:
        link.unlink()


def test_listing_the_run_shows_observations_only(generated_run):
    from state.run_view import open_run

    view = open_run(generated_run.paths.root)
    assert set(view.files) == {
        "sensors.json",
        "feed_log.csv",
        "feed_assays.csv",
        "operator_notes.json",
    }
    assert not [f for f in view.files if "truth" in f]


def test_the_loader_returns_the_observations_it_is_meant_to(generated_run):
    """The refusals above would be trivial if the loader returned nothing at all."""
    from state.run_view import open_run

    view = open_run(generated_run.paths.root)
    sensors = view.sensors()["sensors"]
    assert set(sensors) == set(generated_run.record.names)
    assert view.sensor("gas_flow")["unit"]
    assert view.feed_log()
    assert view.operator_notes() is not None
    assert view.manifest.plant == "C"


def test_the_manifest_a_workflow_sees_has_no_field_for_the_answer(generated_run):
    """The truth store's manifest carries the scenario, the seeds and the fault layers.

    The projection has no field for any of them — not even one that happens to be absent
    from this particular file, which is why ``hasattr`` is asserted as well as membership.
    """
    from sim.run.manifest import REDACTED_FIELDS
    from state.run_view import open_run

    complete = json.loads(generated_run.paths.truth_manifest.read_text(encoding="utf-8"))
    assert set(complete) >= REDACTED_FIELDS, "the stored manifest is supposed to be complete"

    public = open_run(generated_run.paths.root).manifest
    dumped = public.model_dump()
    for field in REDACTED_FIELDS:
        assert field not in dumped, field
        assert not hasattr(public, field), field
    # and no seed value has leaked into it under another name. `replicate` is excluded:
    # it is an index, not a secret, and its value 0 collides with every other zero.
    from sim.run.seeds import STREAM_ORDER

    secret = {str(complete["seeds"][name]) for name in (*STREAM_ORDER, "base")}
    assert not secret & {str(v) for v in dumped.values()}


# --- ruling B5 (ii): the visible plant contract is qualitative about its baselines -------


_PLANT_CONFIGS = sorted((REPO_ROOT / "configs" / "plants").glob("plant_*.yaml"))

# Names that belong to the truth-side record and must not appear in a visible plant file,
# in code, comments or prose: the adapted constant, the biomass states whose ratio names
# the baseline, and the record's own field names.
_TRUTH_SIDE_WORDS = ("K_I_nh3", "X_ac", "X_sao", "expected_digestate_tan", "adaptation:")


def test_the_visible_plant_contract_carries_no_numeric_baseline_table():
    """Ruling B5 (ii): baselines are declared qualitatively; the numbers are truth-side.

    Three checks, one per way the numbers could come back: the schema forbids the fields
    (``adaptation``, ``expected_digestate_tan``), so a table cannot be loaded; the raw file
    text spells none of the truth-side names, so a table cannot hide in a YAML comment;
    and no digit appears in any baseline's description or note, so a number cannot be
    written into the prose. The truth record itself is the negative control: it carries
    every one of those names and numbers, and the harness reads it.
    """
    import yaml

    from sim.plants import load_plant_config
    from sim.plants.schema import Baseline
    from sim.plants.truth import TRUTH_RECORD_DIR, load_plant_truth

    assert set(Baseline.model_fields) == {"name", "description", "note"}
    assert _PLANT_CONFIGS, "no plant contracts found"
    checked_baselines = 0
    for path in _PLANT_CONFIGS:
        text = path.read_text(encoding="utf-8")
        for word in _TRUTH_SIDE_WORDS:
            assert word not in text, (path.name, word)
        raw = yaml.safe_load(text)
        for entry in raw.get("baselines", []):
            assert set(entry) <= {"name", "description", "note"}, (path.name, sorted(entry))
            prose = entry["description"] + entry.get("note", "")
            assert not any(ch.isdigit() for ch in prose), (path.name, entry["name"], prose)
            checked_baselines += 1
    assert checked_baselines >= 2, "Plant A's two baselines must be declared"

    # the negative control: the record has what the contract does not, and the harness
    # gets the adapted constant from it
    plant = load_plant_config("A")
    record_path = TRUTH_RECORD_DIR / "plant_A.yaml"
    record_text = record_path.read_text(encoding="utf-8")
    assert all(word in record_text for word in _TRUTH_SIDE_WORDS[:4]), "record is not complete"
    assert _TRUTH_PATH.search(str(record_path)), record_path  # the checker would flag its path
    record = load_plant_truth(plant)
    assert {b.name for b in record.baselines} == {b.name for b in plant.baselines}
    assert record.baseline("adapted").adaptation.K_I_nh3 > 0.0


def test_the_truth_side_record_and_the_contract_must_agree(tmp_path):
    """A record describing baselines the contract does not declare (or vice versa) is refused."""
    import yaml

    from sim.plants import load_plant_config
    from sim.plants.truth import TRUTH_RECORD_DIR, load_plant_truth

    plant = load_plant_config("A")
    raw = yaml.safe_load((TRUTH_RECORD_DIR / "plant_A.yaml").read_text(encoding="utf-8"))
    raw["baselines"] = raw["baselines"][:1]  # drops `unadapted`
    (tmp_path / "plant_A.yaml").write_text(yaml.safe_dump(raw), encoding="utf-8")
    with pytest.raises(ValueError, match="must agree"):
        load_plant_truth(plant, tmp_path)
    # no record at all for a plant that declares baselines is an error, not a silent default
    with pytest.raises(ValueError, match="no truth record"):
        load_plant_truth(plant, tmp_path / "empty")
    # and a plant that declares none has none, without complaint
    assert load_plant_truth(load_plant_config("B"), tmp_path / "empty") is None


def test_opening_something_that_is_not_a_run_fails_loudly(tmp_path):
    from state.run_view import open_run

    with pytest.raises(FileNotFoundError):
        open_run(tmp_path)
    (tmp_path / "observations").mkdir()
    with pytest.raises(FileNotFoundError, match="manifest"):
        open_run(tmp_path)
