"""Enforce CLAUDE.md rule 1: hidden truth is never readable by workflows.

Ground truth is written only to ``runs/<id>/truth/``. The rule is enforced twice over,
because either check alone is weak:

**Statically.** Nothing under ``workflows/`` may import a ``truth`` module or reference a
path with a ``truth`` segment. The check is AST-based, so it covers code that is never
executed in tests. Its blind spot is a path assembled at run time, and it says nothing
about whether the API a workflow is *given* can hand truth over.

**On the real API.** The second half of this file drives
:func:`state.run_view.open_run` — the loader a workflow actually uses — against a run
generated by the harness, and asks it for hidden truth in every way a caller could:
by relative path, by traversal, by absolute path, by symlink, by listing, and by reading
the manifest fields that would give the answer away. All of it fails, and the same run's
truth is shown to be sitting on disk and readable by anything that is not the loader, so
the test is not passing merely because there is nothing there to find.

The checker is exercised against synthetic violating and clean files first, so the static
half cannot pass simply because ``workflows/`` is still mostly empty.
"""

from __future__ import annotations

import ast
import json
import re
from dataclasses import dataclass
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
WORKFLOWS_DIR = REPO_ROOT / "workflows"

# A path-like string literal with "truth" as a segment: "runs/x/truth/", "/truth",
# "truth/params.json", or the bare segment "truth" (as in Path(run) / "truth").
_TRUTH_PATH = re.compile(r"(?i)(^|[/\\])truth([/\\]|$)")


@dataclass(frozen=True)
class Violation:
    """One forbidden reference to hidden truth."""

    path: Path
    line: int
    kind: str
    detail: str

    def __str__(self) -> str:
        """Format as file:line: kind: detail."""
        return f"{self.path}:{self.line}: {self.kind}: {self.detail}"


def _docstring_nodes(tree: ast.AST) -> set[int]:
    """Return ids of string constants that are docstrings, which are exempt."""
    exempt: set[int] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Module | ast.ClassDef | ast.FunctionDef | ast.AsyncFunctionDef):
            body = node.body
            if (
                body
                and isinstance(body[0], ast.Expr)
                and isinstance(body[0].value, ast.Constant)
                and isinstance(body[0].value.value, str)
            ):
                exempt.add(id(body[0].value))
    return exempt


def find_truth_references(path: Path) -> list[Violation]:
    """Statically find imports of, or path references to, hidden truth in one module.

    Args:
        path: A Python source file.

    Returns:
        Every violation found, in source order.
    """
    source = path.read_text(encoding="utf-8")
    tree = ast.parse(source, filename=str(path))
    exempt = _docstring_nodes(tree)
    found: list[Violation] = []

    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                if "truth" in alias.name.lower().split("."):
                    found.append(Violation(path, node.lineno, "import", alias.name))
        elif isinstance(node, ast.ImportFrom):
            module = (node.module or "").lower()
            segments = module.split(".") if module else []
            names = [alias.name.lower() for alias in node.names]
            if "truth" in segments or "truth" in names:
                names_str = ", ".join(alias.name for alias in node.names)
                found.append(
                    Violation(path, node.lineno, "import", f"from {node.module} import {names_str}")
                )
        elif (
            isinstance(node, ast.Constant)
            and isinstance(node.value, str)
            and id(node) not in exempt
            and _TRUTH_PATH.search(node.value)
        ):
            found.append(Violation(path, node.lineno, "path literal", repr(node.value)))

    return found


def workflow_modules() -> list[Path]:
    """Every Python module under workflows/, recursively."""
    return sorted(WORKFLOWS_DIR.rglob("*.py"))


# --- self-check: the checker must catch each forbidden pattern -----------------------

_VIOLATING_SOURCE = '''
"""Docstring mentioning runs/<id>/truth/ is allowed."""
import sim.truth
from sim import truth
from sim.truth.model import TruthModel
from pathlib import Path

def load(run: Path):
    a = open(run / "truth" / "params.json")
    b = open(f"{run}/truth/labels.json")
    c = open("/data/runs/abc/TRUTH/x.yaml")
    d = run.joinpath("truth")
    return a, b, c, d
'''

_CLEAN_SOURCE = '''
"""Ground truth is discussed here in a docstring only; that is fine."""
from pathlib import Path

from tools import registry

def load(run: Path):
    # "truthful" and "untruth" are not path segments and must not be flagged.
    label = "truthful"
    obs = open(run / "observations.csv")
    return registry, label, obs, "untruth"
'''


def test_checker_catches_every_forbidden_pattern(tmp_path: Path):
    bad = tmp_path / "bad_workflow.py"
    bad.write_text(_VIOLATING_SOURCE, encoding="utf-8")
    kinds = [v.kind for v in find_truth_references(bad)]
    assert kinds.count("import") == 3, kinds
    # "truth" (joined), "/truth/" (f-string part), "/TRUTH/", "truth" (joinpath)
    assert kinds.count("path literal") == 4, kinds


def test_checker_ignores_docstrings_and_near_misses(tmp_path: Path):
    good = tmp_path / "good_workflow.py"
    good.write_text(_CLEAN_SOURCE, encoding="utf-8")
    assert find_truth_references(good) == []


# --- the rule itself -------------------------------------------------------------


def test_workflows_layout_exists():
    assert WORKFLOWS_DIR.is_dir()
    for sub in ("p0_scripted", "p1_single_agent", "p2_multi_agent"):
        assert (WORKFLOWS_DIR / sub / "__init__.py").is_file(), sub


def test_no_workflow_module_references_hidden_truth():
    modules = workflow_modules()
    assert modules, "workflows/ contains no Python modules to check"
    violations = [v for path in modules for v in find_truth_references(path)]
    assert not violations, "workflows/ must not touch hidden truth:\n" + "\n".join(
        str(v) for v in violations
    )


# --- the rule on the real API ----------------------------------------------------
#
# Everything below drives the loader a workflow is actually given, on a run the harness
# actually generated. A static scan cannot show that this loader is unable to return
# truth; only asking it can.


@pytest.fixture(scope="module")
def generated_run(tmp_path_factory):
    """A real run on disk: truth written, observations written, manifest written."""
    from scenarios.schema import load_scenario
    from sim.plants import load_plant_config
    from sim.run.harness import generate_run

    scenario = load_scenario(REPO_ROOT / "scenarios" / "S2-03.yaml")
    scenario = scenario.model_copy(update={"duration_days": 40.0, "faults": ()})
    return generate_run(
        scenario,
        "B",
        plant=load_plant_config("C"),
        runs_root=tmp_path_factory.mktemp("runs"),
    )


def test_the_truth_really_is_on_disk(generated_run):
    """The negative results below must not pass because there is nothing there."""
    truth = generated_run.paths.truth
    assert truth.is_dir()
    payload = json.loads(generated_run.paths.truth_faults.read_text(encoding="utf-8"))
    assert payload["scenario_id"] == "S2-03"
    assert payload["truth_label"] == ["sensor"]
    geometry = json.loads(generated_run.paths.truth_geometry.read_text(encoding="utf-8"))
    assert geometry["V_liq_true_m3"] > 0.0  # the hidden active volume, plainly readable


@pytest.mark.parametrize(
    "asked_for",
    [
        "../truth/faults.json",
        "../truth/parameters.json",
        "..",
        "../manifest.json",
        "./../truth/geometry.json",
        "../../etc/passwd",
        "/etc/passwd",
    ],
)
def test_the_workflow_loader_cannot_be_asked_for_truth(generated_run, asked_for):
    """Every spelling of "give me the truth" fails the same way."""
    from state.run_view import TruthAccessError, open_run

    view = open_run(generated_run.paths.root)
    with pytest.raises(TruthAccessError):
        view.read_text(asked_for)


def test_a_symlink_out_of_the_observations_does_not_open_a_door(generated_run):
    """Resolution happens before the containment check, so a link is not an escape."""
    from state.run_view import TruthAccessError, open_run

    link = generated_run.paths.observations / "shortcut"
    try:
        link.symlink_to(generated_run.paths.truth, target_is_directory=True)
    except (OSError, NotImplementedError):  # pragma: no cover - platform without symlinks
        pytest.skip("symlinks unavailable")
    try:
        view = open_run(generated_run.paths.root)
        with pytest.raises(TruthAccessError):
            view.read_text("shortcut/faults.json")
    finally:
        link.unlink()


def test_listing_the_run_shows_observations_only(generated_run):
    from state.run_view import open_run

    view = open_run(generated_run.paths.root)
    assert set(view.files) == {
        "sensors.json",
        "feed_log.csv",
        "feed_assays.csv",
        "operator_notes.json",
    }
    assert not [f for f in view.files if "truth" in f]


def test_the_loader_returns_the_observations_it_is_meant_to(generated_run):
    """The refusals above would be trivial if the loader returned nothing at all."""
    from state.run_view import open_run

    view = open_run(generated_run.paths.root)
    sensors = view.sensors()["sensors"]
    assert set(sensors) == set(generated_run.record.names)
    assert view.sensor("gas_flow")["unit"]
    assert view.feed_log()
    assert view.operator_notes() is not None
    assert view.manifest.plant == "C"


def test_the_manifest_a_workflow_sees_has_no_field_for_the_answer(generated_run):
    """The file carries the scenario, the seeds and the fault layers; the projection does not."""
    from sim.run.manifest import REDACTED_FIELDS
    from state.run_view import open_run

    on_disk = json.loads(generated_run.paths.manifest.read_text(encoding="utf-8"))
    assert set(on_disk) >= REDACTED_FIELDS, "the manifest is supposed to be complete"

    public = open_run(generated_run.paths.root).manifest
    dumped = public.model_dump()
    for field in REDACTED_FIELDS:
        assert field not in dumped, field
        assert not hasattr(public, field), field
    # and no seed value has leaked into it under another name. `replicate` is excluded:
    # it is an index, not a secret, and its value 0 collides with every other zero.
    from sim.run.seeds import STREAM_ORDER

    secret = {str(on_disk["seeds"][name]) for name in (*STREAM_ORDER, "base")}
    assert not secret & {str(v) for v in dumped.values()}


def test_opening_something_that_is_not_a_run_fails_loudly(tmp_path):
    from state.run_view import open_run

    with pytest.raises(FileNotFoundError):
        open_run(tmp_path)
    (tmp_path / "observations").mkdir()
    with pytest.raises(FileNotFoundError, match="manifest"):
        open_run(tmp_path)
