"""Enforce CLAUDE.md rule 1: hidden truth is never readable by workflows.

Ground truth is written only to ``truth_store/<id>/`` — a separate top-level tree, not a
subdirectory of the run (the lead's ruling of 2026-09-04). The rule is enforced three times
over, because each layer alone is weak in a way the next one covers:

**Structurally.** ``runs/<id>/`` holds the observations, the redacted manifest and the call
log, and nothing else. A workflow rooted there has nothing to escape *to*. This is the
layer the review's two bypasses would have hit: it does not depend on the loader being
right, which is exactly why it is first.

**Statically.** Nothing under ``workflows/`` may import a ``truth``/``truth_store`` module
or reference a path with either as a segment. The check is AST-based, so it covers code
that is never executed in tests. Its blind spot is a path assembled at run time — and,
as the review showed, an attribute handed out by an API, which spells nothing at all.

**On the real API.** The last part of this file drives :func:`state.run_view.open_run` —
the loader a workflow actually uses — against a run generated by the harness, and asks it
for hidden truth in every way a caller could: by relative path, by traversal, by ``"."``
and ``""``, by absolute path, by symlink, by listing, by every public attribute and method
the object exposes, by looking for the run root anywhere on the object at all (it is in a
closure, not an attribute), and by reading the manifest fields that would give the answer
away.
All of it fails; the same run's truth is shown to be on disk and readable by anything that
is not the loader; and a **negative control** asserts that a legitimate read still
succeeds, so the test cannot pass by refusing everything.

The checker is exercised against synthetic violating and clean files first, so the static
half cannot pass simply because ``workflows/`` is still mostly empty.
"""

from __future__ import annotations

import ast
import json
import re
from dataclasses import dataclass
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
WORKFLOWS_DIR = REPO_ROOT / "workflows"

# A path-like string literal with "truth" or "truth_store" as a segment: "runs/x/truth/",
# "/truth", "truth_store/params.json", or the bare segment (as in Path(run) / "truth").
_TRUTH_PATH = re.compile(r"(?i)(^|[/\\])truth(_store)?([/\\]|$)")

_TRUTH_MODULES = frozenset({"truth", "truth_store"})


@dataclass(frozen=True)
class Violation:
    """One forbidden reference to hidden truth."""

    path: Path
    line: int
    kind: str
    detail: str

    def __str__(self) -> str:
        """Format as file:line: kind: detail."""
        return f"{self.path}:{self.line}: {self.kind}: {self.detail}"


def _docstring_nodes(tree: ast.AST) -> set[int]:
    """Return ids of string constants that are docstrings, which are exempt."""
    exempt: set[int] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Module | ast.ClassDef | ast.FunctionDef | ast.AsyncFunctionDef):
            body = node.body
            if (
                body
                and isinstance(body[0], ast.Expr)
                and isinstance(body[0].value, ast.Constant)
                and isinstance(body[0].value.value, str)
            ):
                exempt.add(id(body[0].value))
    return exempt


def find_truth_references(path: Path) -> list[Violation]:
    """Statically find imports of, or path references to, hidden truth in one module.

    Args:
        path: A Python source file.

    Returns:
        Every violation found, in source order.
    """
    source = path.read_text(encoding="utf-8")
    tree = ast.parse(source, filename=str(path))
    exempt = _docstring_nodes(tree)
    found: list[Violation] = []

    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                if _TRUTH_MODULES & set(alias.name.lower().split(".")):
                    found.append(Violation(path, node.lineno, "import", alias.name))
        elif isinstance(node, ast.ImportFrom):
            module = (node.module or "").lower()
            segments = set(module.split(".")) if module else set()
            names = {alias.name.lower() for alias in node.names}
            if _TRUTH_MODULES & (segments | names):
                names_str = ", ".join(alias.name for alias in node.names)
                found.append(
                    Violation(path, node.lineno, "import", f"from {node.module} import {names_str}")
                )
        elif (
            isinstance(node, ast.Constant)
            and isinstance(node.value, str)
            and id(node) not in exempt
            and _TRUTH_PATH.search(node.value)
        ):
            found.append(Violation(path, node.lineno, "path literal", repr(node.value)))

    return found


def workflow_modules() -> list[Path]:
    """Every Python module under workflows/, recursively."""
    return sorted(WORKFLOWS_DIR.rglob("*.py"))


# --- self-check: the checker must catch each forbidden pattern -----------------------

_VIOLATING_SOURCE = '''
"""Docstring mentioning runs/<id>/truth/ is allowed."""
import sim.truth
from sim import truth
from sim.truth.model import TruthModel
from sim.truth_store import load_truth
from pathlib import Path

def load(run: Path):
    a = open(run / "truth" / "params.json")
    b = open(f"{run}/truth/labels.json")
    c = open("/data/runs/abc/TRUTH/x.yaml")
    d = run.joinpath("truth")
    e = open("truth_store/run_abc/parameters.json")
    return a, b, c, d, e
'''

_CLEAN_SOURCE = '''
"""Ground truth is discussed here in a docstring only; that is fine."""
from pathlib import Path

from tools import registry

def load(run: Path):
    # "truthful" and "untruth" are not path segments and must not be flagged.
    label = "truthful"
    obs = open(run / "observations.csv")
    return registry, label, obs, "untruth"
'''


def test_checker_catches_every_forbidden_pattern(tmp_path: Path):
    bad = tmp_path / "bad_workflow.py"
    bad.write_text(_VIOLATING_SOURCE, encoding="utf-8")
    kinds = [v.kind for v in find_truth_references(bad)]
    assert kinds.count("import") == 4, kinds
    # "truth" (joined), "/truth/" (f-string part), "/TRUTH/", "truth" (joinpath),
    # "truth_store/..." (the tree hidden truth actually lives in)
    assert kinds.count("path literal") == 5, kinds


def test_checker_ignores_docstrings_and_near_misses(tmp_path: Path):
    good = tmp_path / "good_workflow.py"
    good.write_text(_CLEAN_SOURCE, encoding="utf-8")
    assert find_truth_references(good) == []


# --- the rule itself -------------------------------------------------------------


def test_workflows_layout_exists():
    assert WORKFLOWS_DIR.is_dir()
    for sub in ("p0_scripted", "p1_single_agent", "p2_multi_agent"):
        assert (WORKFLOWS_DIR / sub / "__init__.py").is_file(), sub


def test_no_workflow_module_references_hidden_truth():
    modules = workflow_modules()
    assert modules, "workflows/ contains no Python modules to check"
    violations = [v for path in modules for v in find_truth_references(path)]
    assert not violations, "workflows/ must not touch hidden truth:\n" + "\n".join(
        str(v) for v in violations
    )


# --- the rule on the real API ----------------------------------------------------
#
# Everything below drives the loader a workflow is actually given, on a run the harness
# actually generated. A static scan cannot show that this loader is unable to return
# truth; only asking it can.


@pytest.fixture(scope="module")
def generated_run(tmp_path_factory):
    """A real run on disk: truth written, observations written, manifest written."""
    from scenarios.schema import load_scenario
    from sim.plants import load_plant_config
    from sim.run.harness import generate_run

    scenario = load_scenario(REPO_ROOT / "scenarios" / "S2-03.yaml")
    scenario = scenario.model_copy(update={"duration_days": 40.0, "faults": ()})
    return generate_run(
        scenario,
        "B",
        plant=load_plant_config("C"),
        runs_root=tmp_path_factory.mktemp("store") / "runs",
    )


def test_the_truth_really_is_on_disk(generated_run):
    """The negative results below must not pass because there is nothing there."""
    truth = generated_run.paths.truth
    assert truth.is_dir()
    payload = json.loads(generated_run.paths.truth_faults.read_text(encoding="utf-8"))
    assert payload["scenario_id"] == "S2-03"
    assert payload["truth_label"] == ["sensor"]
    geometry = json.loads(generated_run.paths.truth_geometry.read_text(encoding="utf-8"))
    assert geometry["V_liq_true_m3"] > 0.0  # the hidden active volume, plainly readable


def test_the_truth_is_not_inside_the_run_directory(generated_run):
    """The structural half of the ruling: there is nothing above the observations to reach.

    The two bypasses the review demonstrated both worked by walking *up* from the
    observations directory. This asserts the layout that makes that pointless: hidden truth
    is in its own top-level tree, and ``runs/<id>/`` contains only the observations, the
    redacted manifest and the call log.
    """
    root = generated_run.paths.root
    truth = generated_run.paths.truth
    assert root not in truth.parents and truth != root
    assert truth.parent.name == "truth_store"
    assert truth.parent.parent == root.parent.parent  # sibling trees, one level up
    assert truth.name == root.name == generated_run.run_id

    inside = {p.relative_to(root).parts[0] for p in root.rglob("*")}
    assert inside == {"observations", "manifest.json", "calls.jsonl"}, sorted(inside)
    # nothing anywhere under the run directory carries a truth quantity
    assert not [p for p in root.rglob("*") if "truth" in p.name.lower()]


def test_the_manifest_under_runs_is_written_redacted(generated_run):
    """Not "redacted on the way out": the file itself never had the answer in it."""
    from sim.run.manifest import REDACTED_FIELDS

    visible = json.loads(generated_run.paths.manifest.read_text(encoding="utf-8"))
    assert not REDACTED_FIELDS & set(visible), sorted(REDACTED_FIELDS & set(visible))
    complete = json.loads(generated_run.paths.truth_manifest.read_text(encoding="utf-8"))
    assert set(complete) >= REDACTED_FIELDS, "the complete manifest belongs in the truth store"
    assert complete["scenario_id"] == "S2-03"
    # and no seed value has leaked into the visible file under another name
    from sim.run.seeds import STREAM_ORDER

    secret = {str(complete["seeds"][name]) for name in (*STREAM_ORDER, "base")}
    assert not secret & {str(v) for v in visible.values()}


# --- the adversarial bypass suite -------------------------------------------------
#
# Every route the review found, plus the ones it did not, plus a NEGATIVE CONTROL. A
# sandbox that refuses everything passes every refusal test ever written; the control is
# what makes the refusals mean something.


@pytest.mark.parametrize(
    "asked_for",
    [
        # traversal, in every spelling
        "../truth/faults.json",
        "../truth/parameters.json",
        "../../truth_store",
        "..",
        "../manifest.json",
        "./../truth/geometry.json",
        "../../etc/passwd",
        "subdir/../../manifest.json",
        # the directory itself: `view.path(".")` was one of the two live bypasses, and it
        # returned a Path whose .parent was the run root
        ".",
        "./",
        "",
        "   ",
        # absolute
        "/etc/passwd",
        "/",
    ],
)
def test_the_workflow_loader_cannot_be_asked_for_truth(generated_run, asked_for):
    """Every spelling of "give me the truth" fails the same way."""
    from state.run_view import TruthAccessError, open_run

    view = open_run(generated_run.paths.root)
    with pytest.raises(TruthAccessError):
        view.read_text(asked_for)
    with pytest.raises(TruthAccessError):
        view.read_json(asked_for)


def test_the_loader_still_reads_what_it_is_for(generated_run):
    """NEGATIVE CONTROL. Without this the suite above passes by refusing everything."""
    from state.run_view import open_run

    view = open_run(generated_run.paths.root)
    record = view.read_json("sensors.json")
    assert record["sensors"], "the loader must still return the observations"
    assert view.read_text("feed_log.csv").startswith("day_d,")
    assert set(view.files) >= {"sensors.json", "feed_log.csv"}


def test_no_public_attribute_of_the_view_hands_over_a_path(generated_run):
    """The other live bypass: ``view.root / "truth" / "parameters.json"``.

    It wrote no forbidden string, so the static checker was blind to it. The rule that
    kills the whole class is that the view returns *contents*, never a path or a directory
    handle — so this walks every public attribute and no-argument method of the object and
    asserts none of them yields one.
    """
    from state.run_view import open_run

    view = open_run(generated_run.paths.root)
    public = [n for n in dir(view) if not n.startswith("_")]
    assert public, "the view exposes nothing at all, which would make this vacuous"

    checked = 0
    for name in public:
        value = getattr(view, name)
        if callable(value):
            try:
                value = value()
            except TypeError:  # takes arguments (e.g. read_text, sensor)
                continue
        checked += 1
        assert not isinstance(value, Path), f"view.{name} returns a Path"
        assert not any(isinstance(v, Path) for v in _leaves(value)), f"view.{name} yields a Path"
    assert checked >= 5, f"only {checked} accessors exercised"


def test_the_run_root_is_not_an_attribute_of_the_view(generated_run):
    """The lead's ruling E: the root is in a closure, not on the object.

    The review's live bypass was a *public* field. Making it private would have left the
    same object graph one underscore away, so there is no attribute at all — not `root`,
    not `_root`, and nothing whose value is the run directory or the observations
    directory.
    """
    from state.run_view import open_run

    view = open_run(generated_run.paths.root)
    for name in ("root", "_root", "_base", "path", "_resolve"):
        assert not hasattr(view, name), name

    # nothing stored on the object IS a path, under any name
    stored = {**getattr(view, "__dict__", {})}
    for field in getattr(view, "__dataclass_fields__", {}):
        stored[field] = getattr(view, field)
    for name, value in stored.items():
        assert not isinstance(value, Path | str), (name, value)

    # and the run directory does not appear as a value anywhere on it
    forbidden = {str(generated_run.paths.root), str(generated_run.paths.observations)}
    assert not forbidden & {str(v) for v in stored.values()}


def test_the_listing_and_the_resolver_agree(generated_run):
    """The lead's ruling E: `files` must not advertise what `read_text` will refuse.

    A planted symlink out of the tree used to be listed and then refused, so the view
    promised something it would not hand over.
    """
    from state.run_view import TruthAccessError, open_run

    link = generated_run.paths.observations / "planted.json"
    try:
        link.symlink_to(generated_run.paths.truth_faults)
    except (OSError, NotImplementedError):  # pragma: no cover - platform without symlinks
        pytest.skip("symlinks unavailable")
    try:
        view = open_run(generated_run.paths.root)
        assert "planted.json" not in view.files
        with pytest.raises(TruthAccessError):
            view.read_text("planted.json")
        # every listed file really is readable — the listing is not empty either
        assert view.files
        for name in view.files:
            assert view.read_text(name) is not None
    finally:
        link.unlink()


def _leaves(value: object, depth: int = 0) -> list[object]:
    """Every scalar reachable inside a returned container, to a bounded depth."""
    if depth > 3:
        return [value]
    if isinstance(value, dict):
        return [leaf for v in value.values() for leaf in _leaves(v, depth + 1)]
    if isinstance(value, list | tuple | set):
        return [leaf for v in value for leaf in _leaves(v, depth + 1)]
    return [value]


def test_a_symlink_out_of_the_observations_does_not_open_a_door(generated_run):
    """Resolution happens before the containment check, so a link is not an escape."""
    from state.run_view import TruthAccessError, open_run

    link = generated_run.paths.observations / "shortcut"
    try:
        link.symlink_to(generated_run.paths.truth, target_is_directory=True)
    except (OSError, NotImplementedError):  # pragma: no cover - platform without symlinks
        pytest.skip("symlinks unavailable")
    try:
        view = open_run(generated_run.paths.root)
        with pytest.raises(TruthAccessError):
            view.read_text("shortcut/faults.json")
        # and a link to a single file, which needs no directory traversal at all
        file_link = generated_run.paths.observations / "answers.json"
        file_link.symlink_to(generated_run.paths.truth_faults)
        try:
            with pytest.raises(TruthAccessError):
                view.read_text("answers.json")
        finally:
            file_link.unlink()
    finally:
        link.unlink()


def test_listing_the_run_shows_observations_only(generated_run):
    from state.run_view import open_run

    view = open_run(generated_run.paths.root)
    assert set(view.files) == {
        "sensors.json",
        "feed_log.csv",
        "feed_assays.csv",
        "operator_notes.json",
    }
    assert not [f for f in view.files if "truth" in f]


def test_the_loader_returns_the_observations_it_is_meant_to(generated_run):
    """The refusals above would be trivial if the loader returned nothing at all."""
    from state.run_view import open_run

    view = open_run(generated_run.paths.root)
    sensors = view.sensors()["sensors"]
    assert set(sensors) == set(generated_run.record.names)
    assert view.sensor("gas_flow")["unit"]
    assert view.feed_log()
    assert view.operator_notes() is not None
    assert view.manifest.plant == "C"


def test_the_manifest_a_workflow_sees_has_no_field_for_the_answer(generated_run):
    """The truth store's manifest carries the scenario, the seeds and the fault layers.

    The projection has no field for any of them — not even one that happens to be absent
    from this particular file, which is why ``hasattr`` is asserted as well as membership.
    """
    from sim.run.manifest import REDACTED_FIELDS
    from state.run_view import open_run

    complete = json.loads(generated_run.paths.truth_manifest.read_text(encoding="utf-8"))
    assert set(complete) >= REDACTED_FIELDS, "the stored manifest is supposed to be complete"

    public = open_run(generated_run.paths.root).manifest
    dumped = public.model_dump()
    for field in REDACTED_FIELDS:
        assert field not in dumped, field
        assert not hasattr(public, field), field
    # and no seed value has leaked into it under another name. `replicate` is excluded:
    # it is an index, not a secret, and its value 0 collides with every other zero.
    from sim.run.seeds import STREAM_ORDER

    secret = {str(complete["seeds"][name]) for name in (*STREAM_ORDER, "base")}
    assert not secret & {str(v) for v in dumped.values()}


def test_opening_something_that_is_not_a_run_fails_loudly(tmp_path):
    from state.run_view import open_run

    with pytest.raises(FileNotFoundError):
        open_run(tmp_path)
    (tmp_path / "observations").mkdir()
    with pytest.raises(FileNotFoundError, match="manifest"):
        open_run(tmp_path)
