"""Typed I/O of every tool (proposal §6.2): Pydantic models with explicit units.

Shared, byte for byte, with the workflow-side client stub (:mod:`tools.client`), so this
package imports **only** the standard library, numpy and pydantic -- never :mod:`sim`,
never the registry. Every numeric field states its unit in its description (CLAUDE.md
rule 6); every output that carries model quantities carries a ``units`` mapping as well,
because a result crosses a process boundary and is read without this module in front of
the reader.

Arrays are :data:`Array` fields: numpy on both sides, lists in JSON, so a model round-trips
through ``model_dump(mode="json")`` / ``model_validate`` unchanged.
"""

from tools.schemas.base import (
    Array,
    ObservedSeries,
    ToolInput,
    ToolOutput,
    Window,
)
from tools.schemas.tools import (
    TOOL_INPUTS,
    TOOL_OUTPUTS,
    AssayResult,
    BayesMCMCInput,
    BayesMCMCOutput,
    DataQCInput,
    DataQCOutput,
    DescribeModelInput,
    DescribeModelOutput,
    FeedLoadsInput,
    FeedLoadsOutput,
    FilterEnKFInput,
    FilterEnKFOutput,
    FilterMHEInput,
    FilterMHEOutput,
    FisherInfoInput,
    FisherInfoOutput,
    FitCMAESInput,
    FitDEInput,
    FitLSQInput,
    FitOutput,
    GSAMorrisInput,
    GSAMorrisOutput,
    GSASobolInput,
    GSASobolOutput,
    MassBalanceInput,
    MassBalanceOutput,
    ProfileLikelihoodInput,
    ProfileLikelihoodOutput,
    RemainingBudget,
    RequestAssayInput,
    RequestAssayOutput,
    ResidualDiagInput,
    ResidualDiagOutput,
    SimulateInput,
    SimulateOutput,
    ValidateInput,
    ValidateOutput,
    VOIAssayInput,
    VOIAssayOutput,
)

__all__ = [
    "TOOL_INPUTS",
    "TOOL_OUTPUTS",
    "Array",
    "AssayResult",
    "BayesMCMCInput",
    "BayesMCMCOutput",
    "DataQCInput",
    "DataQCOutput",
    "DescribeModelInput",
    "DescribeModelOutput",
    "FeedLoadsInput",
    "FeedLoadsOutput",
    "FilterEnKFInput",
    "FilterEnKFOutput",
    "FilterMHEInput",
    "FilterMHEOutput",
    "FisherInfoInput",
    "FisherInfoOutput",
    "FitCMAESInput",
    "FitDEInput",
    "FitLSQInput",
    "FitOutput",
    "GSAMorrisInput",
    "GSAMorrisOutput",
    "GSASobolInput",
    "GSASobolOutput",
    "MassBalanceInput",
    "MassBalanceOutput",
    "ObservedSeries",
    "ProfileLikelihoodInput",
    "ProfileLikelihoodOutput",
    "RemainingBudget",
    "RequestAssayInput",
    "RequestAssayOutput",
    "ResidualDiagInput",
    "ResidualDiagOutput",
    "SimulateInput",
    "SimulateOutput",
    "ToolInput",
    "ToolOutput",
    "VOIAssayInput",
    "VOIAssayOutput",
    "ValidateInput",
    "ValidateOutput",
    "Window",
]
