"""The run manifest: everything needed to reproduce a run, and the subset a workflow sees.

Two objects, **two files**. :class:`RunManifest` is **complete**: the scenario it came
from, every derived seed, the declared fault layers, the content hash of every
configuration file, and the git commit. That is what reproducibility (§13) and evaluation
(§6.7) need.

It is also, in three of those fields, the answer key. The scenario id names the row of the
ladder; the fault layers *are* the uncertainty class a workflow is scored on attributing
(§6.7 B); and the seeds would let a workflow re-run the generator and read the truth off
its own copy. Proposal §10 anticipates this — "agents leak information via prompts (e.g.
scenario names) ... scenario IDs randomised; agents never see YAML". So the complete
manifest is written to ``truth_store/<id>/manifest.json``, with the rest of the hidden
truth, and ``runs/<id>/manifest.json`` holds :class:`PublicManifest` alone: the run's
identity, the plant and tier it is looking at, how long it ran, and the provenance needed
to reproduce the *environment* — never the scenario, the seeds or the faults.

The projection was once made at read time, which meant the secret was on disk inside the
directory a workflow was handed and a containment bug in the loader was all that stood
between the two. Since the lead's ruling of 2026-09-04 the redaction happens at **write**
time as well, so the file a workflow can open never carried the answer in the first place.

The two are kept in one module so the redaction is one diff away from the thing it
redacts: :data:`REDACTED_FIELDS` lists what is dropped, and a test asserts that no field
of :class:`PublicManifest` is one of them and that every field of :class:`RunManifest` is
either public or redacted, so a field added to one cannot be forgotten in the other.
"""

from __future__ import annotations

import hashlib
import json
import os
import subprocess
from pathlib import Path
from typing import Annotated, Self

from pydantic import BaseModel, ConfigDict, Field

__all__ = [
    "HARNESS_VERSION",
    "REDACTED_FIELDS",
    "ConfigVersions",
    "PublicManifest",
    "RunManifest",
    "config_versions",
    "git_sha",
    "write_index_entry",
]

HARNESS_VERSION = "1.0"
"""Version of the run harness itself. Bump when the on-disk contract changes."""

REDACTED_FIELDS: frozenset[str] = frozenset(
    {
        "scenario_id",
        "level",
        "seeds",
        "fault_layers",
        "target_feed",
        "notes_seeded",
        "baseline",
        "created_utc",
    }
)
"""Manifest fields a workflow must never see: they name the scenario, its faults, or the
seeds that would let a workflow regenerate the hidden truth for itself.

``created_utc`` joined the list at the final review of ``99a8947`` (finding F1,
2026-09-10): the matrix is generated in a shuffled order, but the shuffle was seeded with a
committed constant over the public library, so the permutation was reproducible and a sort
of the run set by creation time mapped position to cell exactly — a public salt over a
public space, the same class as B1. The order is now keyed with the store's secret salt
*and* the timestamp is gone from the visible surface (the manifest here, ``t_utc`` in the
visible call log, and every visible file's modification time is set to one fixed instant),
so neither the ordering nor a position carries the cell. The complete manifest keeps it.

``baseline`` is the one that needs an argument, because the plant *contract* declares both
of Plant A's baselines and a workflow is told they exist (lead's ruling 1, 2026-09-09). What
it is not told is **which one this run is staged on**, and the reason is arithmetic rather
than principle: only S6-01 runs on the ``unadapted`` baseline, so the field would name the
scenario outright — exactly the §10 leak the opaque run id and the redacted scenario id
exist to prevent. Which baseline the digester is in is legible from the run's own record
(acetate an order of magnitude apart, at the same gas rate), and working that out is the
diagnostic task, not a thing to be handed over. If a later matrix runs several scenarios on
each baseline the argument weakens and this can be revisited."""


class ConfigVersions(BaseModel):
    """Declared version and content hash of every configuration file a run read.

    The version numbers are the ones the config files carry (``version: 2`` and so on);
    the hashes catch an edit that forgot to bump one. Together they answer "was this run
    generated by the configuration in the tree today?" without storing the files.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    versions: dict[str, int] = Field(
        default_factory=dict, description="Config name -> its declared integer version"
    )
    sha256: dict[str, str] = Field(
        default_factory=dict, description="Config path (repo-relative) -> sha256 of its bytes"
    )


class PublicManifest(BaseModel):
    """What a workflow is told about the run it is looking at.

    Everything here describes the *environment*: which plant, which instrumentation tier,
    how long the record is, and which version of the simulator produced it. Nothing here
    identifies the scenario, its faults or its seeds — nor *when* the run was generated,
    which was its position in the generation order (finding F1).
    """

    model_config = ConfigDict(frozen=True, extra="ignore")

    run_id: str
    plant: str = Field(description="Plant id: A, B or C (its declared config is visible)")
    tier: str = Field(description="Instrumentation tier, A/B/C (§6.4)")
    duration_days: float = Field(description="Length of the observation record, d")
    n_days: int = Field(description="Number of daily influent samples, d")
    start_doy: int = Field(description="Day of year of day 0 (the seasonal phase)")
    start_weekday: int = Field(description="Weekday of day 0, 0 = Monday")
    harness_version: str
    git_sha: str
    configs: ConfigVersions

    def write(self, path: Path) -> None:
        """Write the projection as indented JSON.

        This is what lands at ``runs/<id>/manifest.json``. The complete
        :class:`RunManifest` is written to the truth store instead, so the file a workflow
        can open does not merely *omit* the answer, it never contained it.
        """
        path.write_text(self.model_dump_json(indent=2) + "\n", encoding="utf-8")


class RunManifest(BaseModel):
    """The complete provenance of one run (``runs/<id>/manifest.json``)."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    run_id: str
    scenario_id: str = Field(description="REDACTED from the workflow's view")
    level: Annotated[int, Field(ge=0, le=8)] = Field(description="REDACTED: rung of the ladder")
    plant: str
    tier: str
    duration_days: float
    n_days: int
    start_doy: int
    start_weekday: int
    seeds: dict[str, int | str] = Field(description="REDACTED: one per stochastic component")
    fault_layers: dict[str, list[str]] = Field(
        description="REDACTED: fault ids by layer (sim.faults.declared_faults)"
    )
    target_feed: str | None = Field(
        default=None, description="REDACTED: the feed an influent fault acts on"
    )
    baseline: str | None = Field(
        default=None, description="REDACTED: the declared plant baseline this run is staged on"
    )
    notes_seeded: int = Field(default=0, description="REDACTED: number of operator notes placed")
    created_utc: str = Field(description="REDACTED: the position in the generation order")
    harness_version: str = HARNESS_VERSION
    git_sha: str
    configs: ConfigVersions

    def public(self) -> PublicManifest:
        """The projection a workflow may see.

        Built by naming the public fields explicitly rather than by deleting the redacted
        ones, so a new secret field is invisible to a workflow by default instead of
        leaking until someone remembers to add it to the deny-list.
        """
        return PublicManifest(
            run_id=self.run_id,
            plant=self.plant,
            tier=self.tier,
            duration_days=self.duration_days,
            n_days=self.n_days,
            start_doy=self.start_doy,
            start_weekday=self.start_weekday,
            harness_version=self.harness_version,
            git_sha=self.git_sha,
            configs=self.configs,
        )

    def write(self, path: Path) -> None:
        """Write the complete manifest as indented JSON.

        Its home is ``truth_store/<id>/manifest.json``: the scenario id, the seeds and the
        fault layers are the answer key, so the complete record lives with the rest of the
        hidden truth and :meth:`public` is what is written under ``runs/``.
        """
        path.write_text(self.model_dump_json(indent=2) + "\n", encoding="utf-8")

    @classmethod
    def read(cls, path: Path) -> Self:
        """Read a manifest written by :meth:`write`."""
        return cls.model_validate_json(Path(path).read_text(encoding="utf-8"))


def git_sha(repo_root: Path | None = None) -> str:
    """The current commit, or ``"unknown"`` outside a git checkout.

    A run generated from a dirty tree is marked ``<sha>-dirty``, because §13 requires
    final runs to come from a tagged release and a manifest that hid the difference would
    make that unverifiable.
    """
    root = repo_root or Path(__file__).resolve().parents[2]
    try:
        sha = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=root,
            capture_output=True,
            text=True,
            check=True,
            timeout=10,
        ).stdout.strip()
        dirty = subprocess.run(
            ["git", "status", "--porcelain"],
            cwd=root,
            capture_output=True,
            text=True,
            check=True,
            timeout=10,
        ).stdout.strip()
    except (OSError, subprocess.SubprocessError):
        return "unknown"
    return f"{sha}-dirty" if dirty else sha


def config_versions(paths: dict[str, Path], versions: dict[str, int]) -> ConfigVersions:
    """Collect declared versions and content hashes of the configuration files of a run.

    Args:
        paths: Config name -> path on disk. A missing file is recorded as ``"absent"``
            rather than raising, so a run is still reproducible-by-description if an
            optional config is not present.
        versions: Config name -> the integer version the file declares.

    Returns:
        The collected record.
    """
    hashes: dict[str, str] = {}
    for name, path in sorted(paths.items()):
        p = Path(path)
        hashes[name] = hashlib.sha256(p.read_bytes()).hexdigest()[:16] if p.is_file() else "absent"
    return ConfigVersions(versions=dict(sorted(versions.items())), sha256=hashes)


def write_index_entry(index_path: Path, entry: dict[str, object]) -> None:
    """Record one run in the evaluator's ``truth_store/index.jsonl``.

    The index maps an opaque run id back to its cell, which is why it lives in the truth
    store rather than beside the runs: it names the scenario of every run.

    **One line per run id, not one per write.** A run id is a hash of its cell
    (:func:`sim.run.layout.run_id`), so regenerating a cell overwrites its own directories;
    an index that merely appended would then carry the cell twice and an evaluator counting
    its lines would over-count every regenerated cell. Any existing line for this run id is
    replaced in place, so the index says what is on disk however often it was written.

    Args:
        index_path: The index file.
        entry: The run's index record; its ``run_id`` is the key.
    """
    index_path.parent.mkdir(parents=True, exist_ok=True)
    line = json.dumps(entry, separators=(",", ":"), sort_keys=True)
    run = entry.get("run_id")
    kept: list[str] = []
    replaced = False
    if index_path.is_file():
        for existing in index_path.read_text(encoding="utf-8").splitlines():
            if not existing.strip():
                continue
            try:
                same = json.loads(existing).get("run_id") == run
            except json.JSONDecodeError:
                same = False
            if same:
                kept.append(line)
                replaced = True
            else:
                kept.append(existing)
    if not replaced:
        kept.append(line)
    # Written to a sibling temp file and moved into place, so a reader -- or a second
    # generator process -- never sees a half-written id->cell map, and a crash mid-write
    # leaves the previous index intact rather than an empty file (review, 2026-09-10; no
    # ruling needed). os.replace is atomic on POSIX and on NTFS.
    tmp = index_path.with_name(index_path.name + ".tmp")
    tmp.write_text("\n".join(kept) + "\n", encoding="utf-8")
    os.replace(tmp, index_path)
