"""The run manifest: everything needed to reproduce a run, and the subset a workflow sees.

Two objects for one file. :class:`RunManifest` is written to ``runs/<id>/manifest.json``
and is **complete**: the scenario it came from, every derived seed, the declared fault
layers, the content hash of every configuration file, and the git commit. That is what
reproducibility (§13) and evaluation (§6.7) need.

It is also, in three of those fields, the answer key. The scenario id names the row of the
ladder; the fault layers *are* the uncertainty class a workflow is scored on attributing
(§6.7 B); and the seeds would let a workflow re-run the generator and read the truth off
its own copy. Proposal §10 anticipates this — "agents leak information via prompts (e.g.
scenario names) ... scenario IDs randomised; agents never see YAML" — so the manifest is
not handed over as written. :class:`PublicManifest` is the projection a workflow receives
through :mod:`state.run_view`: the run's identity, the plant and tier it is looking at,
how long it ran, and the provenance needed to reproduce the *environment* — never the
scenario, the seeds or the faults.

The two are kept in one module so the redaction is one diff away from the thing it
redacts: :data:`REDACTED_FIELDS` lists what is dropped, and a test asserts that no field
of :class:`PublicManifest` is one of them and that every field of :class:`RunManifest` is
either public or redacted, so a field added to one cannot be forgotten in the other.
"""

from __future__ import annotations

import hashlib
import json
import subprocess
from pathlib import Path
from typing import Annotated, Self

from pydantic import BaseModel, ConfigDict, Field

__all__ = [
    "HARNESS_VERSION",
    "REDACTED_FIELDS",
    "ConfigVersions",
    "PublicManifest",
    "RunManifest",
    "config_versions",
    "git_sha",
    "write_index_entry",
]

HARNESS_VERSION = "1.0"
"""Version of the run harness itself. Bump when the on-disk contract changes."""

REDACTED_FIELDS: frozenset[str] = frozenset(
    {"scenario_id", "level", "seeds", "fault_layers", "target_feed", "notes_seeded"}
)
"""Manifest fields a workflow must never see: they name the scenario, its faults, or the
seeds that would let a workflow regenerate the hidden truth for itself."""


class ConfigVersions(BaseModel):
    """Declared version and content hash of every configuration file a run read.

    The version numbers are the ones the config files carry (``version: 2`` and so on);
    the hashes catch an edit that forgot to bump one. Together they answer "was this run
    generated by the configuration in the tree today?" without storing the files.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    versions: dict[str, int] = Field(
        default_factory=dict, description="Config name -> its declared integer version"
    )
    sha256: dict[str, str] = Field(
        default_factory=dict, description="Config path (repo-relative) -> sha256 of its bytes"
    )


class PublicManifest(BaseModel):
    """What a workflow is told about the run it is looking at.

    Everything here describes the *environment*: which plant, which instrumentation tier,
    how long the record is, and which version of the simulator produced it. Nothing here
    identifies the scenario, its faults or its seeds.
    """

    model_config = ConfigDict(frozen=True, extra="ignore")

    run_id: str
    plant: str = Field(description="Plant id: A, B or C (its declared config is visible)")
    tier: str = Field(description="Instrumentation tier, A/B/C (§6.4)")
    duration_days: float = Field(description="Length of the observation record, d")
    n_days: int = Field(description="Number of daily influent samples, d")
    start_doy: int = Field(description="Day of year of day 0 (the seasonal phase)")
    start_weekday: int = Field(description="Weekday of day 0, 0 = Monday")
    created_utc: str
    harness_version: str
    git_sha: str
    configs: ConfigVersions


class RunManifest(BaseModel):
    """The complete provenance of one run (``runs/<id>/manifest.json``)."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    run_id: str
    scenario_id: str = Field(description="REDACTED from the workflow's view")
    level: Annotated[int, Field(ge=0, le=8)] = Field(description="REDACTED: rung of the ladder")
    plant: str
    tier: str
    duration_days: float
    n_days: int
    start_doy: int
    start_weekday: int
    seeds: dict[str, int | str] = Field(description="REDACTED: one per stochastic component")
    fault_layers: dict[str, list[str]] = Field(
        description="REDACTED: fault ids by layer (sim.faults.declared_faults)"
    )
    target_feed: str | None = Field(
        default=None, description="REDACTED: the feed an influent fault acts on"
    )
    notes_seeded: int = Field(default=0, description="REDACTED: number of operator notes placed")
    created_utc: str
    harness_version: str = HARNESS_VERSION
    git_sha: str
    configs: ConfigVersions

    def public(self) -> PublicManifest:
        """The projection a workflow may see.

        Built by naming the public fields explicitly rather than by deleting the redacted
        ones, so a new secret field is invisible to a workflow by default instead of
        leaking until someone remembers to add it to the deny-list.
        """
        return PublicManifest(
            run_id=self.run_id,
            plant=self.plant,
            tier=self.tier,
            duration_days=self.duration_days,
            n_days=self.n_days,
            start_doy=self.start_doy,
            start_weekday=self.start_weekday,
            created_utc=self.created_utc,
            harness_version=self.harness_version,
            git_sha=self.git_sha,
            configs=self.configs,
        )

    def write(self, path: Path) -> None:
        """Write the manifest as indented JSON."""
        path.write_text(self.model_dump_json(indent=2) + "\n", encoding="utf-8")

    @classmethod
    def read(cls, path: Path) -> Self:
        """Read a manifest written by :meth:`write`."""
        return cls.model_validate_json(Path(path).read_text(encoding="utf-8"))


def git_sha(repo_root: Path | None = None) -> str:
    """The current commit, or ``"unknown"`` outside a git checkout.

    A run generated from a dirty tree is marked ``<sha>-dirty``, because §13 requires
    final runs to come from a tagged release and a manifest that hid the difference would
    make that unverifiable.
    """
    root = repo_root or Path(__file__).resolve().parents[2]
    try:
        sha = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=root,
            capture_output=True,
            text=True,
            check=True,
            timeout=10,
        ).stdout.strip()
        dirty = subprocess.run(
            ["git", "status", "--porcelain"],
            cwd=root,
            capture_output=True,
            text=True,
            check=True,
            timeout=10,
        ).stdout.strip()
    except (OSError, subprocess.SubprocessError):
        return "unknown"
    return f"{sha}-dirty" if dirty else sha


def config_versions(paths: dict[str, Path], versions: dict[str, int]) -> ConfigVersions:
    """Collect declared versions and content hashes of the configuration files of a run.

    Args:
        paths: Config name -> path on disk. A missing file is recorded as ``"absent"``
            rather than raising, so a run is still reproducible-by-description if an
            optional config is not present.
        versions: Config name -> the integer version the file declares.

    Returns:
        The collected record.
    """
    hashes: dict[str, str] = {}
    for name, path in sorted(paths.items()):
        p = Path(path)
        hashes[name] = hashlib.sha256(p.read_bytes()).hexdigest()[:16] if p.is_file() else "absent"
    return ConfigVersions(versions=dict(sorted(versions.items())), sha256=hashes)


def write_index_entry(index_path: Path, entry: dict[str, object]) -> None:
    """Append one line to the evaluator's ``runs/index.jsonl``.

    The index maps an opaque run id back to its cell. It lives at the *root* of the run
    store rather than inside any run, so handing a workflow one run directory hands it
    nothing about the others.
    """
    index_path.parent.mkdir(parents=True, exist_ok=True)
    with index_path.open("a", encoding="utf-8") as fh:
        fh.write(json.dumps(entry, separators=(",", ":"), sort_keys=True) + "\n")
